# Generated by Django 2.2.9 on 2019-12-22 07:45

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='DDKBGene',
            fields=[
                ('EnsemblId', models.CharField(blank=True, default='', max_length=100, null=True, verbose_name='Ensemble数据库中对基因的命名')),
                ('Symbol', models.CharField(blank=True, default='', max_length=100, null=True, verbose_name='危险基因名称')),
                ('EntrezId', models.CharField(max_length=100, primary_key=True, serialize=False, verbose_name='基因的唯一标识符')),
                ('Chr', models.CharField(blank=True, default='', max_length=100, null=True, verbose_name='基因在染色体上的位置')),
                ('Start', models.CharField(blank=True, default='', max_length=100, null=True, verbose_name='起始点')),
                ('End', models.CharField(blank=True, default='', max_length=100, null=True, verbose_name='终止点')),
            ],
            options={
                'verbose_name': '基因信息',
                'verbose_name_plural': '基因信息',
            },
        ),
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=70)),
                ('body', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='UserMessage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('object_id', models.CharField(max_length=50, verbose_name='主键')),
                ('name', models.CharField(blank=True, default='', max_length=20, null=True, verbose_name='用户名')),
                ('email', models.EmailField(max_length=254, verbose_name='邮箱')),
                ('address', models.CharField(max_length=100, verbose_name='联系地址')),
                ('message', models.CharField(max_length=500, verbose_name='留言信息')),
            ],
            options={
                'verbose_name': '用户留言信息',
                'verbose_name_plural': '用户留言信息',
            },
        ),
    ]
